### ISSUE TITLE
`artifactWebpackStatsFile` is not used

### ISSUE THREAD

**Issue by bramkragten** [relative-ci/agent-action#274]
It seems like `artifactWebpackStatsFile` is never used, but instead `webpackStatsFile` is used.

Both the documentation and the error logs indicate it should be `artifactWebpackStatsFile`.

https://github.com/relative-ci/agent-action/blob/master/src/index.ts#L46

**Comment by vio** [comment]
Hi @bramkragten, thanks for opening an issue!

You are right, `artifactWebpackStatsFile` is not used anymore. If I remember correctly, it was part of the RC for v2, but we decided that we could reuse `webpackStatsFile`. Will remove it ;)

**Comment by bramkragten** [comment]
Thanks for your quick response, it seems you missed one place though:

https://github.com/relative-ci/agent-action/blob/f2aebf9b1c7dc74b660245e6d63b00f31b7f3242/src/artifacts.ts#L78
