### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by bazylhorsey** [relative-ci/agent-action#308]
I have set up the integration on Github, and the RELATIVE_CI_KEY is in the github environment variables. This is a private repository, and GITHUB_TOKEN is not in Actions environment variables because it should be implicit.

```
Run relative-ci/agent-action@v[2](https://github.com/ArvistDev/arvist-stack/actions/runs/8209974397/job/22456730989#step:2:2)
  with:
    key: ***
    token: ***
    includeCommitMessage: true
    debug: false
Error: HttpError: Resource not accessible by integration
```

```yml
name: RelativeCI
 
on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types:
      - completed
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send bundle stats and build information to RelativeCI
        uses: relative-ci/agent-action@v2
        with:
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by vio** [comment]
thanks for creating the issue @bazylhorsey!

It looks like one of the few GitHub API operations is failing due to a lack of permissions. Would it be possible to give it a try with `debug: true`  and another one with `includeCommitmessage: false`?
